#!/bin/bash

# SETUP THE PRE-COMMIT HOOK:
# git config core.hooksPath .githooks

#echo "Updating devicelist submodule..."
#git submodule update --remote --merge
#git add devicelist
#echo "devicelist submodule updated."

# echo "Getting install script for Packages"
# mkdir -p ./install

# URL="https://raw.githubusercontent.com/NovodoOfficial/novodo-packages/main/install.sh"
# TARGET="./install/packages.sh"

# echo "Trying to download install script from $URL..."
# if curl -fsSL "$URL" -o "$TARGET"; then
#     echo "Downloaded packages install script to $TARGET"
# else
#     echo "WARNING: Failed to download install script from $URL"
#     echo "Keeping existing $TARGET if it exists."
#     if [ ! -f "$TARGET" ]; then
#         echo "#!/bin/bash" > "$TARGET"
#         echo "# Empty install script placeholder." >> "$TARGET"
#         echo "Created empty $TARGET"
#     fi
# fi

# git add "$TARGET"
# echo "Added $TARGET to the commit"

# exit 0
